injectEnvironmentFiles:
  - .env

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  mystikonetwork:
    npmRegistryServer: "https://npm.pkg.github.com/"
