name: Build
env:
  GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.targets }}
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.0.2 --activate
      - name: Make env
        run: echo "" >> .env
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Setup Registry
        run: |
          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN }}" >> $HOME/.npmrc
      - name: Install dependencies
        run: yarn install
      - name: Lint all
        run: yarn lint
      - name: Build all
        run: yarn build
      - name: Test all
        run: yarn test
      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: Telegram Success Notification
        uses: appleboy/telegram-action@master
        if: success()
        with:
          message: Build succeeded for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions)
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
